# @package _global_

fps: 30

env:
  name: gym-isaacsim
  task: LiftCube-v0
  state_dim: 13
  action_dim: 7
  fps: ${fps}
  episode_length: 150
  # gym:
  #   obs_type: pixels_agent_pos
  #   render_mode: rgb_array
